// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6ZI7is_llIiqZuYCk1v_UVcJ5O1sMJzE',
    appId: '1:103023698604:web:edf4b76a0fb909d5797509',
    messagingSenderId: '103023698604',
    projectId: 'docmanager-6515a',
    authDomain: 'docmanager-6515a.firebaseapp.com',
    storageBucket: 'docmanager-6515a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqskiLQG5OFuEnokZLNFyKFImR5zAV58E',
    appId: '1:103023698604:android:4dbea2351eb35625797509',
    messagingSenderId: '103023698604',
    projectId: 'docmanager-6515a',
    storageBucket: 'docmanager-6515a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBelHtWEoXrFxvElXr3k98Yhv8qr4c98pE',
    appId: '1:103023698604:ios:739d39a30d3688e8797509',
    messagingSenderId: '103023698604',
    projectId: 'docmanager-6515a',
    storageBucket: 'docmanager-6515a.appspot.com',
    iosBundleId: 'com.example.ytEcommerceAdminPanel',
  );
}
